# 예외처리

```
public class Sample {
    public void shouldBeRun() {
        System.out.println("ok thanks.");
    }

    public static void main(String[] args) {
        Sample sample = new Sample();
        int c;
        try {
            c = 4 / 0; // 해당 구문에서 예외가 발생하고
        } catch (ArithmeticException e) { // 발생한 예외가 해당 예외가 맞으면
            c = -1; // 이 구문이 수행된다
        } finally {
            sample.shouldBeRun();  // 예외에 상관없이 무조건 수행된다.
        }
    }
}
```

**try**

- 예외가 발생할 수 있는 코드를 실행시킨다
- 예외가 발생하지 않으면 정상 실행, 발행하면 catch 에서 예외를 받는다

**catch**

- 예외가 일어날 수 있는 코드가 실행되면 실행된다
- catch 아래 있는 코드가 실행되며
- catch(예외) 안에 특정 예외 ( ArithmeticException 등 ) 의 객체를 넣으면 해당 예외가 발생할때만 해당 catch 문이 작동한다
- 객체를 넣는 것이기 때문에 ArithmeticException e 처럼 해당 객체의 자료형을 미리 선언해준다

**finaly**

- try…catch 문이 끝이나고 난 뒤에도 꼭 작동해야하는 코드를 실행한다
- .close() 같은 어떤일이 특정 프로세스가 끝나고 꼭 작동해야하는 코드가 있으면 넣어두면 된다

**RuntimeExcrption 과 Exception**

- RuntimeException 은 파일의 실행중에 생기는 예외이다
- 예외처리를 강제하지 않는다
- Exception 은 컴파일 도중에 생기는 예외이다
- 예외처리를 하지 않을 시 컴파일이 되지 않으므로 예외처리를 강제한다

**throws 와  throw**

- **throws**
    - 예외를 넘긴다/던진다
    - 해당 메소드를 사용할 때 메소드 내부에서 해당 예외가 발생하면 메소드가 예외로 나온다
    - 즉 위 메소드를 **사용하는 곳**에서 해당 예외를 처리해주어야 한다

```
 public void someMethod() throws SomeException {
 }
```

- **throw**
    - 예외를 생성한다
    - try 내에서 예외가 생기면 catch 로 간다
    - 이때 throw 로 특정 **예외를 만들어**줄 수 있다

```
public void someMethod() {
    try {
        . . .
        throw new SomeException;
    }
    catch (SomeException e) {

    }
```

**트랜잭션 transaction**

- 하나의 작업단위

```
상품발송() {
    포장();
    영수증발행();
    발송();
}

포장() {
   ...
}

영수증발행() {
   ...
}

발송() {
   ...
}
```

- 상품발송 이라는 하나의 트랜잭션에서
- 각각의 세부작업 중 하나의 작업이라도 실패하면 상품발송이라는 하나의 트랜잭션을 전부 취소시켜야 한다
    - 이런식으로 하나의 일이 잘못되었을 경우 모든 작업을 취소하고 처음으로 돌아가는것을 **롤백 Rollback** 이라고 한다
- 각각의 작업에서 throws 로 예외를 보내고 상품발송 트랜잭션에서 try…catch 를 해 주면 셋 중 하나의 예외만 발생해도 예외처리를 하게된다
- 하지만 각각의 작업에서 각각 예외처리를 해 주게되면 상품발송에서는 이전 작업이 예외처리되었음에도 다음작업이 실행되는 경우가 생길 수 있다